apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    name: proxy
    author: abhi

spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxy
  template:
    containers:
      - name: nginx-pod
        image: nginx
        ports:
          - containerPort: 80
            hostPort: 8888