---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    types: db
    author: abhi
spec:
  containers:
    - name: my-db
      image: mysql
      env:
        name: MYSQL_ROOT_PASSWORD
        valueForm:
          secretKey:
            name: mysql-secret # this is from Secret1.yml
            key: a
...