---
apiVersion: v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    types: db
    author: abhi

spec:
  replicas: 3
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: my-pod
      labels:
        types: db
    spec:
      containers:
        - name: my-db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueForm:
                secretKey:
                  name: postgress-secret2
                  key: password
            - name: POSTGRES_USER
              valueForm:
                secretKey:
                  name: postgress-secret2
                  key: username
            - name: POSTGRES_DB
              valueForm:
                secretKey:
                  name: postgress-secret2
                  key: mydb